### ISSUE TITLE
Missing some UTF-8 characters in response

### ISSUE THREAD

**Issue by goodspeed34** [gemrest/september#1] opened 2023-05-13 15:00 UTC
Chinese characters are missing in response.

Version:  fuwn/september:latest (b2f2143c0fbd)

Step to replicate:
1. Make a file which contains such characters. This hello world for example:
```
你好世界
```
2. Access it from september.

**Comment by Fuwn** [comment] 2023-06-20 10:21
Thanks for bringing this to my attention, @goodspeed34!

Turns out the issue traced back to a dependency, [Germ](https://github.com/gemrest/germ). I went ahead and fixed the issue at the source and updated the dependency version requirement here, within September.

The issue is now fixed as of commit 4edc119c44168c71c353a09a206ad2e552cf9384 and tag [`v0.2.10`](https://github.com/gemrest/september/releases/tag/v0.2.10).

Expect the Docker images to be updated accordingly momentarily.

**Closed by Fuwn** 2023-06-20 10:21 UTC
